name: CI

on:
  # Zorg dat je de workflow kan triggeren door te pushen of gewoon door op een knop te duwen
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Begin met een workflow met 1 job die runt op een ubuntu runner.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Het project gebruikt gradle om de Kotlin testen te runnen. Je zal dus gradle en java moeten installeren, doe dit elk in een stap met behulp van bestaande actions.
      # Installeer java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Installeer Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.12'

      # Run de testen met de gradle wrapper (./gradlew build).
      - name: Run tests
        run: ./gradlew build
