name: CI

on:
  # Zorg dat je de workflow kan triggeren door te pushen of gewoon door op een knop te duwen
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # Begin met een workflow met 1 job die runt op een ubuntu runner.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #run ./build_version.sh and save the output in a variable
      - name: Get build version
        id: build_version
        run: echo "::set-output name=version::$(./build_version.sh)"

      - name: Git tag
        run: git tag ${{ steps.build_version.outputs.version }}

      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Push to Maaikes main branch. New version: ${{ steps.build_version.outputs.version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
